In [6]:
from MyRoberta import *
from config import *

In [9]:
config = RobertaConfig()
Roberta_LP = MyRobertaForQuestionAnswering_LP.from_pretrained(config.model)

Some weights of the model checkpoint at roberta-base were not used when initializing MyRobertaForQuestionAnswering_LP: ['lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.dense.weight', 'lm_head.bias', 'lm_head.decoder.weight', 'lm_head.layer_norm.bias']
- This IS expected if you are initializing MyRobertaForQuestionAnswering_LP from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing MyRobertaForQuestionAnswering_LP from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of MyRobertaForQuestionAnswering_LP were not initialized from the model checkpoint at roberta-base and are newly initialized: ['qa_outputs.weight', 'qa_outputs.bias']
You should probably TRAIN this model on a down-stream tas

In [16]:
for name, param in Roberta_LP.named_parameters():
    # if "qa_outputs" in name:
    print(name)

roberta.embeddings.word_embeddings.weight
roberta.embeddings.position_embeddings.weight
roberta.embeddings.token_type_embeddings.weight
roberta.embeddings.LayerNorm.weight
roberta.embeddings.LayerNorm.bias
roberta.encoder.layer.0.attention.self.query.weight
roberta.encoder.layer.0.attention.self.query.bias
roberta.encoder.layer.0.attention.self.key.weight
roberta.encoder.layer.0.attention.self.key.bias
roberta.encoder.layer.0.attention.self.value.weight
roberta.encoder.layer.0.attention.self.value.bias
roberta.encoder.layer.0.attention.output.dense.weight
roberta.encoder.layer.0.attention.output.dense.bias
roberta.encoder.layer.0.attention.output.LayerNorm.weight
roberta.encoder.layer.0.attention.output.LayerNorm.bias
roberta.encoder.layer.0.intermediate.dense.weight
roberta.encoder.layer.0.intermediate.dense.bias
roberta.encoder.layer.0.output.dense.weight
roberta.encoder.layer.0.output.dense.bias
roberta.encoder.layer.0.output.LayerNorm.weight
roberta.encoder.layer.0.output.LayerNorm

In [7]:
config = RobertaConfig()

In [8]:
config.model

'roberta-base'

In [47]:
Roberta_LP.qa_outputs.state_dict()['bias'] = torch.tensor([1.,1.])

In [45]:
list(Roberta_LP.qa_outputs.named_parameters())

[('weight',
  Parameter containing:
  tensor([[ 0.0177,  0.0017, -0.0465,  ..., -0.0113, -0.0181, -0.0318],
          [-0.0065,  0.0213,  0.0531,  ..., -0.0098, -0.0057,  0.0294]],
         requires_grad=True)),
 ('bias',
  Parameter containing:
  tensor([0., 0.], requires_grad=True))]

In [48]:
Roberta_LP.qa_outputs.state_dict()

OrderedDict([('weight',
              tensor([[ 0.0177,  0.0017, -0.0465,  ..., -0.0113, -0.0181, -0.0318],
                      [-0.0065,  0.0213,  0.0531,  ..., -0.0098, -0.0057,  0.0294]])),
             ('bias', tensor([0., 0.]))])

In [ ]:
Roberta_LP.qa_outputs.load_state_dict()

In [52]:
3/20

0.15